### ISSUE TITLE
Make Eclipse shutdown faster if intervals cannot be persisted.

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#129]
This is only slow when there is no network connection.

We could e.g. abort the whole process after we have experienced two Network Errors.

**Comment by Inventitech** [comment]
When there are a lot of intervals to transfer, shutdown of Eclipse is slowed down by WatchDog.

In IntervalTransferManager#transferIntervals are divided down to the single interval-level even in case of a Network Error. However, it would be sufficient to check if there is a network error once before beginning the transfer, and if there is an error, stall the transfer all together (leaving the not-transfered intervals in-cache).

**Comment by nspruit** [comment]
@Inventitech does this issue actually still exists? Because when I shut down Eclipse without a network connection, it logs that there was an error, but it closes immediately. The `ServerCommunicationException` that indicates a network error is also raised immediately, although `NetworkUtils.createPlainHttpClient` specifies a 12s timeout on the HttpClient.

**Comment by Inventitech** [comment]
Yes. The scenario is where your computer thinks that you have a 
connection, but it is extremely slow or one where at least the DNS is 
extremely slow. To test this, just ride on an NS train ;-).

Moritz

On 09.12.2015 11:36, Niels Spruit wrote:
>
> @Inventitech <https://github.com/Inventitech> does this issue actually 
> still exists? Because when I shut down Eclipse without a network 
> connection, it logs that there was an error, but it closes 
> immediately. The |ServerCommunicationException| that indicates a 
> network error is also raised immediately, although 
> |NetworkUtils.createPlainHttpClient| specifies a 12s timeout on the 
> HttpClient.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TestRoots/watchdog/issues/129#issuecomment-163183592>.
>

-- 
Please change my address in your address books to moritz.beller@googlemail.com.
Bitte meine Adresse auf moritz.beller@googlemail.com ändern.

**Comment by nspruit** [comment]
Haha thanks, then I'll try to simulate this scenario and find a way to shorten the shutdown time.
