### ISSUE TITLE
Extend WatchDog Statistics View

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#140]
Our WatchDogStatistics View shows some basic visualizations to our users.

![image](https://cloud.githubusercontent.com/assets/334256/5488236/28f829a6-86bb-11e4-998a-b680fe791dac.png)

As we process more interesting data than what we currently display, it would be nice to extend our visualization. In particular, these two additional visualizations would be nice to have:
- How long developers spend in different perspectives (to assess how much of their time they are actually debugging). This could be done nicely with a Pie Chart showing the relative amounts of time.
- The number of Junit executions normalized e.g. per hour.

**Comment by levaja** [comment]
Can you explain what exactly do you mean by "the number of Junit executions normalized e.g. per hour"?

I am not sure is it a total number of tests executed in the last hour, or number of Junit intervals per hour, or maybe a speed of tests/hour, based on ratio (number of tests):(interval duration)?

**Comment by levaja** [comment]
I have added these visualization [in my repository](https://github.com/levaja/watchdog). However, I am not really happy with the visualization of number of executions (see the image below). Do you have any suggestion? Adding something more to it, or maybe use different representation?
![overview](https://cloud.githubusercontent.com/assets/5550526/5629377/0eba3af0-95b3-11e4-97ea-5a1ed51df45b.png)

**Comment by Inventitech** [comment]
Hi Igor,

Nice!

Please change "Your Perspective View Activity" to "Your Perspective Activity". View and perspective are two different, but related concepts in Eclipse and therfore should not be mixed.

How about adding the average execution runtime of the Junit Executions (field `JUnitInterval.duration`)? Since the y-axis is unitless, this might work well quite well. 

Please replace Junit Executions by Test Runs in the title and diagram description, and change the title to Your Test Run Activity.

**Comment by levaja** [comment]
Hi Moritz,

Thanks for feedback!

Here is how it looks now:
![avg](https://cloud.githubusercontent.com/assets/5550526/5645113/a4ae58d0-966b-11e4-9aaa-68327efaed2c.png)

It is showing average duration in minutes. Maybe it would be better to show it in seconds?

**Comment by Inventitech** [comment]
> It is showing average duration in minutes. Maybe it would be better to show it in seconds?

It might be a good idea to compare which of the values is closest to each other, and then display it this way. Pseudo-Code following:

```
diffSeconds = Math.abs(avgTestDurationInSeconds - numberOfTestRuns)
diffMinutes = Math.abs(avgTestDurationInMinutes - numberOfTestRuns)

if(diffSeconds < diffMinutes)
 displaySeconds
 description += "(in seconds)"
else
 displayMinutes
 description += "(in minutes)"
```

**Comment by levaja** [comment]
![minsec](https://cloud.githubusercontent.com/assets/5550526/5648016/4c12ef68-968b-11e4-9e9f-a2c73b441f05.png)
I hope it looks better now. Still, it's not perfect (for runs of ~30 seconds it would need 15 runs to change display to minutes), but this will mostly depend on the use-case scenario (run lengths and number of runs can vary a lot, I guess).

**Comment by Inventitech** [comment]
Thanks for implementing this. If you feel your code is of good enough quality, you can file a PR and I'll review it.
