### ISSUE TITLE
WatchDog Statistics View only displays statistics on the last hour of work

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#141]
It might be nicer for the user to be able to choose between different intervals, let's say for example between `10 minutes, 30 minutes, 1 hour, 2 hours, 5 hours, 8 hours and 10 hours`. Can you implement such a toggle in the WatchDogView?

N.b. that this requires a small change to the IntervalPersister for the statistics.

**Comment by levaja** [comment]
I did it this way:
![intervals](https://cloud.githubusercontent.com/assets/5550526/5701785/956c6324-9a50-11e4-8e59-fd0a9145edcf.png)

I will go through code one more time, and if you agree, I can add this to the existing PR #142 , since it is related to Extending Statistics View.

**Comment by Inventitech** [comment]
Nice, this is exactly how I imagined it to be! I'd may be redesign the bottom area to something like "Show statistics of the past " <Selection box> <Refresh_Link>.

Of course, even then, the toggle is not as prominent as it could be -- if you have an idea how to redesign the layout of the view to fix this, please go ahead.

**Comment by levaja** [comment]
Maybe adding some short label to it? Like "Last"? Not really sure what else can be added (or redesigned) in that area - at the moment it is simple and clean and I don't think we can make it different a lot.

Also, selecting another interval refreshes the view; with refresh button it stays in the last selected interval. Default is still 1 hour, and intervals are removed from database after 10 hours (longest interval at the moment). I hope this is the behaviour that you had in mind?

**Comment by Inventitech** [comment]
I just noticed that GH has eaten part of my comment (the ones wrapped in Chevrons), so here it goes again:

I'd may be redesign the bottom area to something like "Show statistics of the past " {the selection box} {the refresh label}.

> Also, selecting another interval refreshes the view; with refresh button it stays in the last selected interval. 
Can you make this consistent, i.e. no update without hitting Refresh?

**Comment by levaja** [comment]
Well, selection box really stands out from the text, but I will try to add this with label and post a screenshot.

Also, regarding behaviour, it appears logical to me that selecting an interval automatically updates the view (also faster, 2 clicks instead of 3) - refresh link is just for refreshing currently selected interval. It's not a problem to remove this behaviour from selection box (one line of code), just this way seems smoother.

**Comment by levaja** [comment]
Maybe something like this:
![1](https://cloud.githubusercontent.com/assets/5550526/5703228/4fc3513e-9a64-11e4-8597-310606f51f90.png)
or
![2](https://cloud.githubusercontent.com/assets/5550526/5703229/54d94c82-9a64-11e4-932e-57465af8921e.png)

**Comment by Inventitech** [comment]
Last option LGTM. Maybe add a fullstop after the selection box? Maybe you can also change the text above to "Showing statistics from ... to ... (x intervals)." (1 line)

**Comment by levaja** [comment]
![3](https://cloud.githubusercontent.com/assets/5550526/5703386/4c8a89f4-9a66-11e4-9c62-cf5641058bf0.png)
This fullstop doesn't look nice, maybe I can include it in selection box, or omit it.

**Comment by Inventitech** [comment]
Also note the gap at the beginning of the line ;-)

**Comment by levaja** [comment]
I know, but at the moment, I have no idea what is causing that gap, still looking into this :)

**Comment by Inventitech** [comment]
Have you looked at UIUtils#createZeroMarginGridedComposite?

**Comment by levaja** [comment]
Exactly what I've missed :+1: 

![4](https://cloud.githubusercontent.com/assets/5550526/5703770/fe74281a-9a6a-11e4-8e06-7e29cd82ca43.png)

In this preview, I added a fullstop to list, do you think it's better there, or after the list, or to omit it?

**Comment by levaja** [comment]
At the moment, there are 2 open questions here:
- Should the View be refreshed on changing intervals (explained [in this comment](https://github.com/TestRoots/watchdog/issues/141#issuecomment-69564345) why) or not?
- Position of fullstop - in the list, after the list or without it (if we omit it, we can put colon after the label, like `Show statistisc of the past:`
After that, I will submit a PR, so we can see is there anything else that could be fixed/enhanced.

**Comment by Inventitech** [comment]
I'd suggest the following:

- No auto-refreshment of the view upon selecting a new time span.
- I like the fullstop in the list.

**Comment by levaja** [comment]
Thanks!
Fixed. I will open a PR now.
