### ISSUE TITLE
Create 1.2.1 Release

### ISSUE THREAD

**Issue by levaja** [TestRoots/watchdog#145]

**Comment by levaja** [comment]
@Inventitech  Should text in License be updated with the current year (2015) ?

**Comment by Inventitech** [comment]
Good idea. Please also add yourself as an author. :)
Am 14.01.2015 20:32 schrieb "Igor Levaja" <notifications@github.com>:

**Comment by levaja** [comment]
I've sent you an email regarding this, have you seen it? :)

**Comment by Inventitech** [comment]
Oh, you can add yourself at the position you feel most comfortable about :)

**Comment by levaja** [comment]
Done. I've also fixed two minor mistakes in JavaDoc, which I've found (https://github.com/levaja/watchdog/commit/ba25388d112d2d5370c5a8f89b921869c7c6bf70 ).
