### ISSUE TITLE
Providing empty string or wrong formed link for Server-URL in Preferences causes an error

### ISSUE THREAD

**Issue by levaja** [TestRoots/watchdog#148]
After URL is deleted, plugin automatically puts " / " as an URL. If it is left like that, the following things happen:

- WatchDog window is empty and unresponsive.

- It is not possible to open WatchDog with a click on the icon.

- It is not possible to close Eclipse due to an error: "Target host is null".

The only fix is to open Preferences from Eclipse (Window -> Preferences), select WatchDog preferences, and then to provide (any) valid URL (for example, it is fine if there's no server on the provided URL, for example http://www.google.com/, as long as the URL is correct; however watchdog.testroots.org/ without a prefix causes the error).

**Comment by Inventitech** [comment]
@levaja this turned out to be quite an involved fixed. Can you review this, please?
