### ISSUE TITLE
False user registrations

### ISSUE THREAD

**Issue by levaja** [TestRoots/watchdog#153]
Hitting Back button on  New User Registration page makes false user registration on the server.

**Comment by levaja** [comment]
Fixed in #154

**Comment by Inventitech** [comment]
I'm not going to bump the WD version, as this has only implications for people who have not yet registered. I'm simply updating the current version on the update site instead and restarting the server.

**Comment by levaja** [comment]
Sounds good :+1: 
I guess that false registrations on server can be safely deleted as well.
