### ISSUE TITLE
Watchdog update reminder appearing too often

### ISSUE THREAD

**Issue by ankon** [TestRoots/watchdog#156]
I've been running watchdog 1.2.mumble, and today switched my eclipse version from 4.5M4 to 4.5M6. Usually when I do that I reinstall all plugins from their sources, this time I tried using Eclipse's "Import from existing installation". Worked mostly, except that this seemed to forget to import the update sites (bad Eclipse, going to look into that!).

In the new installation the watchdog update reminder popped up, asking about whether I want to update. Clicking "Yes" leads to "No updates found" (due to issue above: no update site), and a few moments later the update reminder came back. I clicked "No" this time, as it was actually interrupting me while I was configuring update sites. Still, the reminder simply came back another moment later. So, I went ahead, configured the update site, executed the update (another reminder popup appearing while this was going on!). Eclipse wanted to restart, but given that I still had other update sites to add I postponed that. ... Sure enough, a few moments later the reminder popped up again!

From my point of view I hated watchdog right there: 
1. Why is the reminder a modal dialog?
2. Why does it not check the results of the operation?
3. Why does it not back off when I have interacted with it for at least a day or week when I interacted with it, regardless of the answer I gave?
4. Why does it not know that its update is in the "pending for restart" state?

With that said, I think there is really some "easy" improvements possible here:
1. Make the watchdog-specific update checker configurable, and allow me to disable it. Ideally of course: tie the default into the existing setting of eclipse about "Automatic Updates". I already have that configured, and it's nice and unobtrusive.
2. Check whether the update is available via p2, not via a independent query (or, given that p2 is probably heavy: validate against p2 whether it is really available to be installed)
3. Remember when the dialog was shown to the user last, and block it from appearing for a longer while, regardless of the answer the user gave.

**Comment by Inventitech** [comment]
Thanks for reporting and diving deep into this, Andreas.

Fortunately, this "update-eager" behavior of WatchDog has already been fixed in 1.3. The problem was that the answer to the update question was not cached (as you suspected).
