### ISSUE TITLE
Running tests causes modifications to database files, leaving them modified in git

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#164]
However, we really do not want to check these modifications into the index. Git ignoring is not an option, as we need the files in the index (and they are there anyway), and "unwatching" the files only works locally.

**Comment by Inventitech** [comment]
Answered my own StackOverFlow question: http://stackoverflow.com/questions/29768952/run-tests-from-junit-base-class-before-tests-from-subclass/29772250#29772250

**Comment by Inventitech** [comment]
@levaja, could you review this please?

**Comment by levaja** [comment]
Of course!
