### ISSUE TITLE
Operating system in user registration can be wrong

### ISSUE THREAD

**Issue by levaja** [TestRoots/watchdog#170]
In [this line](https://github.com/TestRoots/watchdog/blob/master/WatchDogEclipsePlugin/WatchDog/src/nl/tudelft/watchdog/ui/wizards/userregistration/UserRegistrationPage.java#L134), OS is determined with `Platform.getOS();`. 

However, in my case (Win 7 64bit) it returns "win32", which is caused (I guess) by Eclipse 32bit version. Maybe we can consider using:
`System.getProperty("os.name")` (returns "Windows 7" in my case) and `System.getProperty("os.arch")` (returns "amd64")?

**Comment by Inventitech** [comment]
I don't think this is a problem. The string is consistent across 32 and 64 bit versions, and we're not interested in the arch anyway. You can replace win32 by win internally, if that makes your brain happier :-)

To go into more detail, on 64-bit windowses, there is a layer called WOW64 which provides backward compatibility with win32.

**Comment by levaja** [comment]
Okay, I was not really sure that this is important, but I wanted to mention it, just in case :) Thanks!
