### ISSUE TITLE
Self-sign eclipse plugins to get rid of unsigned content warning message during install

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#185]
https://nirmalsasidharan.wordpress.com/2010/09/04/signing_eclipse_plugins/

**Comment by Inventitech** [comment]
I think we can start doing this with WD 1.5

**Comment by levaja** [comment]
Will add this :+1:

**Comment by levaja** [comment]
Unfortunately, it is not possible to add this feature to the build process. It's not hard to manually execute it, but should be done after build is finished.

**Comment by Inventitech** [comment]
Yup, that is not a problem. Since we sign off every release manually anyway :)

**Comment by Inventitech** [comment]
see email

**Comment by levaja** [comment]
Yes, I will look into it.

**Comment by levaja** [comment]
Eclipse plugin now comes with a certificate from CA, I think this issue is resolved now :)
