### ISSUE TITLE
Add silent registrations

### ISSUE THREAD

**Issue by levaja** [TestRoots/watchdog#196]
At the moment, if a user cancels the registration wizard, he will not be registered on the server and won't be able to see statistics (because WatchDog will not be active).

However, if someone is not willing to complete the wizard, he'd still maybe be interested in his statistics - that can be achieved with "silent  registrations". 

My proposal is the following: if a user cancels the wizard, he will be asked if he'd still want WatchDog to be active. If he selects "Yes", we will register completely anonymous user and project ids and we will still be able to collect intervals, while he'd be able to see offline statistics and maybe (some parts of) the online report.

@Inventitech Let me know what you think about this, especially about the report - will lack of user/project info make generating report impossible (so we can omit that option)?

**Comment by Inventitech** [comment]
:+1: Go ahead.

**Comment by levaja** [comment]
Can you just let me know about the report - should those anonymous users be able to see it, considering the fact that they don't provide any info (using tests, following TDD, time estimation etc.)?

If not, should I add some field to their project registration, which will tell server not to generate report for them?

**Comment by Inventitech** [comment]
No, we'll keep everything as-is. Report generation should work fine.

**Comment by levaja** [comment]
Okay, thanks, working on this now!

**Comment by levaja** [comment]
Right now, if a user hits Cancel, he'll be asked if he wants to have WD running and, if yes, anonymous registration is executed. If he says no, we do nothing (although we can register his ids then as well, what do you think?).
