### ISSUE TITLE
In silent registrations, project are not registered properly

### ISSUE THREAD

**Issue by levaja** [TestRoots/watchdog#199]
This resulted in more user than project registrations. I'm not 100% sure what is the issue because I am not able to reproduce it, but some possible points will be addressed in the upcoming commit.

**Comment by levaja** [comment]
@gousiosg I think you might be the right person to ask this question.  Is it possible that on WatchDogServer, if a user and a project are registered quickly one after another, server does not store new user ID in the database before it starts registration of the project (hence rejecting this project registration because of the still nonexistent user ID)?

**Comment by gousiosg** [comment]
If you are doing this serially (first, a request to register the user and after this succeeds, a request to register a project), then this should not be an issue. Moreover, the database is not relational, so it should not have issues with primary/foreign keys.

**Comment by levaja** [comment]
In silent registrations, we should make a small time-out and also avoid project registration if user registration fails.

**Comment by levaja** [comment]
I think I have finally been able to reproduce this issue locally (or at least something similar).

On my local server, I tried to simultaneously perform silent registrations (both user and project, one after another) in iterations of 100 and 1000 in a single thread and in separate threads.

Single threaded registrations work well (one thread registers 1000 users and projects), but with 1000 threads results show that:

1) Around 200-300 users are registered (out of expected 1000).
2) Only 15-65 projects are registered (out of expected 1000, or at least 200-300).

I've tried with adding a timeout between user and project registration (up to 5000 ms, which does not block the whole IDE because it is executed in a separate thread), but that didn't help a lot (314 users, 178 projects). Every time I started with an empty database, which on the real server won't be the case.

**Comment by Inventitech** [comment]
Nice! So there is some problem in the communication and/or on the server. One thought could be that the server under load simply takes very long to respond, and the IDE timesout? Or does the acknowledgement on the server side never arrive?

**Comment by gousiosg** [comment]
A way to model this would be to make user registration a strict dependency to project registration. So first ensure that the user is registered and only when this function finishes start the project registration. In pseudocode:

```ruby
def ensure_project(user, project_name)
a = ensure_user(user)

if a.nil?
  nil
else
 register(project)
end
```
There is no way any multithreading can go around this :-) BTW, both `ensure_user` and `ensure_project` need to be idempotent.

**Comment by Inventitech** [comment]
We already do this. Lines 130 and following in watchdog_server.rb

```Ruby
   associated_user = get_user_by_id(project['userId'])
    if associated_user.nil?
      halt 404, "The user who registers the project does not exist on the server. Create a new user first."
    end
```

@levaja: What does the server (do|return) in these cases?

M.

**Comment by levaja** [comment]
Well, I'm trying to figure that out, but simple output shows:

`nl.tudelft.watchdog.core.logic.network.ServerCommunicationException: Failed to commuincate with our server. Read timed out` 

or

`nl.tudelft.watchdog.core.logic.network.ServerCommunicationException: Failed to commuincate with our server. Connect to 192.168.56.101:3000 [/192.168.56.101] failed: connect timed out`

for user registrations. The same occur for project registrations, plus: 

`Project: nl.tudelft.watchdog.core.logic.network.ServerCommunicationException: Failed to execute request on server (status code: 404). The user who registers the project does not exist on the server. Create a new user first.`

**Comment by gousiosg** [comment]
@Inventitech I was taking about doing this at the client side. The errors that @levaja reports indicate that this is not done at the client side.

@levaja Could this be because you do not start more than 1 server instances in your testing environment?

**Comment by Inventitech** [comment]
@gousiosg Same code is obviously present on the client side. 

Seems server when under load cannot perform the registrations fast enough. So in that case, we need a new server @azaidman

**Comment by Inventitech** [comment]
Jokes apart, can we make the registrations on the client side such that it asks the server again if nothing came back. But maybe the server would eventually reply? Can you log whether the server got the incoming request and eventually handled it? That would suck.

**Comment by gousiosg** [comment]
@Inventitech Is it? So why does the `The user who registers the project does not exist on the server. Create a new user first.` error shows up?

**Comment by Inventitech** [comment]
It never shows up.

**Comment by gousiosg** [comment]
? See @levaja 's previous error msg

**Comment by Inventitech** [comment]
Ouch, true.

**Comment by levaja** [comment]
@gousiosg I only have 1 server running locally, I thought that it's the same on TestRoots server.

`The user who registers the project does not exist on the server. Create a new user first. ` shows when project registrations goes through, but previous user registration failed (therefore, there's no user id on server). This can/will be fixed in client code (currently, it's assumed that userId is returned successfully).

**Comment by gousiosg** [comment]
@levaja Ok, so I would re-write the client code as per the pseudocode above before proceeding with further stress testing

**Comment by Inventitech** [comment]
Again, this is already in the client!

**Comment by levaja** [comment]
We can potentially make (in client code) an option to retry registration one (or few) more time(s) if it fails in the first time. However, there's no guarantee that it will succeed later.

This can also be performed in a separate thread (without bothering user to wait for it). I think it shouldn't affect usual WatchDog behavior.

**Comment by Inventitech** [comment]
@levaja What really strikes me is that 1) some user registrations do not seem to work. I mean, what is going on there? 2) why the registering of a new project id does not work and erroneously returns that the user does not exist, even though we know it exists (in fact, we just created it and got a positive reply).

M.

**Comment by Inventitech** [comment]
One random thought: We also start the server with 6 workers. Does this behavior still occur with 1? 
https://github.com/TestRoots/watchdog/blob/master/WatchDogServer/unicorn.rb

**Comment by levaja** [comment]
Actually, for 2), it can happen that project registrations are received by server for the user id that has not been registered successfully (and this will be fixed by forbidding project registrations in case user reg. has failed). However, 1) still can be the problem, I'm not really sure what's the issue here (maybe too many network connections). 

It's interesting also that in my setup, 100 user+project registrations are handled perfectly, which is not the case for 1000.

**Comment by levaja** [comment]
Well, locally, I'm using production mode (with 6 workers), I will test with 1 as well and report it.

**Comment by gousiosg** [comment]
@Inventitech @levaja see lines [103-119](https://github.com/TestRoots/watchdog/blob/master/WatchDogIntelliJPlugin/WatchDog/src/nl/tudelft/watchdog/intellij/WatchDog.java#L103-L119) of `intellij/WatchDog.java`. It does not seem that a valid user registration is ensured before a project registration attempt, as the result of `registerNewUser` is not checked before `registerNewProject` is called.

**Comment by levaja** [comment]
Yes, as I said, that will be fixed (also mentioned in [my comment](https://github.com/TestRoots/watchdog/issues/199#issuecomment-152257685) ).

**Comment by levaja** [comment]
Okay, in case that user registration fails, project registrations is not performed (there's also no error about "user does not exist on the server"). We get 570 users and 280 projects registered in this case. With 1 worker, we get 469 users and 204 projects.

**Comment by levaja** [comment]
The best ratio I could get is: 655 users, 425 projects.

This can be achieved by:

1) Try to register user ID.
2) If it fails, wait for some time (like 1 second) and try again.
3) If it fails, abandon registration. Otherwise, continue with project registration.
4) In case that a user id has been registered, try to register a project id.
5) If it fails, wait for some time and try again.
6) If it fails, nothing...

Maybe this solution will work in real world, do you think we can try with it?

**Comment by Inventitech** [comment]
Why not try to exhaustion (or at least something close to it, like 10
times)?
Am 02.11.2015 5:18 nachm. schrieb "Igor Levaja" <notifications@github.com>:

**Comment by levaja** [comment]
We can, of course, but I'm only afraid if that can make registration slower (if we have to wait 1 second 10 times). 

Actually, since we are not yet sure what is causing this issue on TestRoots server, we don't know how many times (and for how long) should we try to register.

**Comment by levaja** [comment]
Okay, another finding, while I was trying to implement 10-times-retry registration:

Setup: 1000 threads (and this holds for almost any number of threads larger than 100), try to register user and project id; if it fails they try 10 more times with a random waiting interval between attempts (0-5 seconds).

Result in database: every time, number of users is around 1350, and number of projects is 1200±100.

I've checked everything in client side multiple times and finally got to the conclusion that 997 user ids have been received (99.7% successful).  That means that more than 300 user ids have been registered on server, even though there was an exception thrown.

It's a bit hard to debug what goes wrong here, because this happens only if we have more than 100 threads.

**Comment by levaja** [comment]
In my testing,  I made a small mistake - although I'm always really careful, somehow in Eclipse TestRoots server URL slipped through instead of my local one, causing 162 false user registrations (I stopped immediately when I saw something is wrong). 

They are all made from my VPN IP address (therefore, it's really easy to filter them).  I've double checked and all registrations from this IP were made during these ~45 seconds.

Is it okay to use `db.users.remove({"ip":"46.166.188.218"})` on TestRoots database? 

However, one good thing that I've learnt from this mistake is that during these ~45 seconds of intensive registrations, 162 users were registered, but not a single project id!

**Comment by Inventitech** [comment]
Not a problem. Please also add a time constraint to the query.
Am 03.11.2015 3:20 nachm. schrieb "Igor Levaja" <notifications@github.com>:

**Comment by levaja** [comment]
Unfortunately, I'm not authorized to execute this command, but I've prepared the query, so it can be executed whenever you or @gousiosg have time:

`db.users.remove({"ip":"46.166.188.218", "regDate": {$gte : new ISODate("2015-11-03T13:50:00.000Z"), $lte : new ISODate("2015-11-03T13:52:00.000Z")}})`

**Comment by Inventitech** [comment]
`> db.users.remove({"ip":"46.166.188.218", "regDate": {$gte : new ISODate("2015-11-03T13:50:00.000Z"), $lte : new ISODate("2015-11-03T13:52:00.000Z")}})
WriteResult({ "nRemoved" : 162 })`

**Comment by levaja** [comment]
Thanks, sorry for bothering you while enjoying the Eclipse Conference :)

**Comment by levaja** [comment]
What is the meaning of this timeout on the Server:
https://github.com/TestRoots/watchdog/blob/master/WatchDogServer/unicorn.rb#L6

Maybe it's what we need, @Inventitech ?

**Comment by Inventitech** [comment]
Good question. @gousiosg, what does this do exactly (set *which* timeout)?

**Comment by gousiosg** [comment]
IIUC, this means that if a worker process takes more than 15 secs to respond, it gets killed by the supervisor. See also:

http://unicorn.bogomips.org/Unicorn/Configurator.html#method-i-timeout
https://devcenter.heroku.com/articles/request-timeout

**Comment by Inventitech** [comment]
:+1: 

What about nginx or Sintatra timeouts, do you know anything about that?

**Comment by Inventitech** [comment]
I think this is fixed.
