### ISSUE TITLE
Test with IntelliJ 14

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#214]

**Comment by Inventitech** [comment]
Great. Applying this to my local changes, and:

Testing with IJ 15 (141) passed.

Testing with IJ 14 (139) passed.* Does this mean it is IJ 13 compatible or should we change the minimum required IJ build to from 131 to 139? Once I have an answer from you, I will release 1.6!

* But only because @Overrides do not appear in ByteCode, otherwise IntelliJActivationListener would not work. This is also the reason why I opted for this solution, and not the Adapter solution.

**Comment by levaja** [comment]
Well, I would suggest to update the minimum required version. We already have some version-specific code for IJ14 and IJ15, if IJ13 has different API that would create too much noise. 

Furthermore, IntelliJ always notifies users about the updates, so I am pretty sure that developers tend to use the newest version.

**Comment by levaja** [comment]
I've checked, we use some methods that were introduced in IJ14, so we should not support IJ13 anymore.
