### ISSUE TITLE
Use WatchDog for monitoring testing practices in Android Application development

### ISSUE THREAD

**Issue by levaja** [TestRoots/watchdog#229]
Since Android applications are written in Java, and Android Studio is based on IntelliJ IDEA, it should be interesting to support this with WatchDog  (and probably easy to implement).

**Comment by Inventitech** [comment]
Good idea!

**Comment by Inventitech** [comment]
Cool thing about this solution is that it adds 0 effort on the release process, but lets us distinguish between regular IntelliJ and AndroidStudio :+1:
