### ISSUE TITLE
Make Debug non-horizontally filling

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#247]
One thing that still bugs me is the debug visualization :). I think it looks really ugly :D, and I think it is indeed slightly (!) nicer when not stretched horizontally. I also don't really feel comfortable using WD any more, because it's kinda difficult to use on my Laptop now: see the scroll bars when using IntelliJ's default setup of views on a 1920 resolution (I believe it is important support this resolution properly). I think it means that you'd have to undo a few of the changes I suggested. Sorry about this.

![screenshot from 2016-04-20 11-47-51](https://cloud.githubusercontent.com/assets/334256/14670583/05c8767a-06ee-11e6-9416-08c715ca517e.png)

Did you also observe that every Debug perspective displays these events at the end (luckily, they are not transfered to the server)? You can get them by "interactively" modifying the Gantt chart graph (zooming in-out by selecting a region in the plot).

![screenshot from 2016-04-20 11-51-04](https://cloud.githubusercontent.com/assets/334256/14670703/8075e092-06ee-11e6-9532-68b7fd959e58.png)

**Comment by Inventitech** [comment]
Moreover, when I select a time frame for the display of the statistics, this is nicely reflected in the available debug intervals, but even when no debug intervals exists (such as in the example shown below), the debug vis. appears and shows something (which, time-wise, is even outside of the chosen boundary)?

![screenshot from 2016-04-20 11-54-13](https://cloud.githubusercontent.com/assets/334256/14670783/d6d0f314-06ee-11e6-8f92-d700acc1b55f.png)

**Comment by nspruit** [comment]
@Inventitech: do you like this better?:

![ij suggestion](https://cloud.githubusercontent.com/assets/3593160/14674793/025ae564-0706-11e6-92a7-fca958037150.png)

**Comment by nspruit** [comment]
> Did you also observe that every Debug perspective displays these events at the end (luckily, they are not transfered to the server)? You can get them by "interactively" modifying the Gantt chart graph (zooming in-out by selecting a region in the plot).

Didn't observe that before, because I even didn't know that you can actually zoom :-)
But I do have an idea where those "ghost events" come from, so I'll see if I can fix this tomorrow morning.

> Moreover, when I select a time frame for the display of the statistics, this is nicely reflected in the available debug intervals, but even when no debug intervals exists (such as in the example shown below), the debug vis. appears and shows something (which, time-wise, is even outside of the chosen boundary)?

That's strange, as the debug chart and the interval selection dropdown shouldn't appear when there are no debug intervals (see `WatchDogView.createActiveView`). Are you sure no debug intervals existed when you refreshed the view?

**Comment by Inventitech** [comment]
> That's strange, as the debug chart and the interval selection dropdown shouldn't appear when there are no debug intervals (see WatchDogView.createActiveView). Are you sure no debug intervals existed when you refreshed the view?

Pretty sure, you can see the drop down menu is empty.

**Comment by nspruit** [comment]
> Pretty sure, you can see the drop down menu is empty.

OK, then I'll look into that as well

**Comment by nspruit** [comment]
Closed by #253
