### ISSUE TITLE
Create easier-to-grasp Debugging Visualizations in IDE

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#248]
Next to the non-horizontally stretched Debugging view, I think, it makes sense to visualize a few more easy-to-grasp things about debugging, like: number of debugging sessions; time spent in debugger (vs. overall active time?); General usage of the different debugger functionalities. It would be cool to divide the WatchDog view stronger into the two categories Testing and Debugging, and introduce a bit of vertical spacing between the two.

I think this can be implemented relatively quickly.

**Comment by nspruit** [comment]
Closed by #253
