### ISSUE TITLE
Users receive email even though they aborted the registration

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#260]
Brought to my attention by @vovak, Thanks!

**Comment by Inventitech** [comment]
We can't technically fix this as we aggressively register users, but we can at least write that in our email.

**Comment by Inventitech** [comment]
@nspruit, could you "review" :) this?

**Comment by nspruit** [comment]
Sure, we can't indeed fix this easily, but I think the description in the registration mail is clear enough to overcome this.
