### ISSUE TITLE
Ignore breakpoint change events with undefined changes

### ISSUE THREAD

**Issue by nspruit** [TestRoots/watchdog#263]
Currently, we record every change to a breakpoint. However, some of these changes have no clear type of change, e.g. when a breakpoint is hit. Therefore, I've introduced the 'undefined' change type. 

Unfortunately, it seems like these events are generated quite often. In the latest database dump, about 45-50% of all recorded events consist of these particular events. As we can't really extract something useful from these events IMO, it might be better to not record them at all and keep the db clean in this way.

**Comment by Inventitech** [comment]
I don't clearly remember when exactly you're creating an undefined breakpoint change? Do they cause a problem? Or are they hard to filter out? I assume not, then I'd say we leave them in and maybe we'll find something useful to do with them later.

**Comment by nspruit** [comment]
We create an 'undefined' type of breakpoint change when the change(s) are not of the types we track. For instance, when a breakpoint is hit it is also changed in a way, but we don't track this change as we already have a SUSPEND_BREAKPOINT debug event that is much easier to recognize. No, they don't cause any problems, but just data we don't use (at least not now). OK, then we'll leave them in, because filtering them out in R is not that hard and is even already part of the 'gen-events-file' script.
