### ISSUE TITLE
Remove capital letters in file path for non-windows machines

### ISSUE THREAD

**Issue by TimvdLippe** [TestRoots/watchdog#267]
Non-windows machines are case-sensitive. To make sure that this project builds on all machines, I propose to change all file paths to lowercase kebab-case. E.g. change `WatchDogCore` to `watch-dog-core`. This makes sure all tools can properly build on this project.

**Comment by Inventitech** [comment]
What's the status on this?

**Comment by TimvdLippe** [comment]
This one was resolved with my packaging refactoring :tada:
