### ISSUE TITLE
Findings listed by Teamscale

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#280]
The recent bunch of changes has introduced a couple of findings in Teamscale, most notably many public methods are left undocumented, which does not need to be changed. The remaining issues are not hard to address.

Steps to fix:
1. Create account for Teamscale on http://demo.teamscale.com
2. Inspect Findings view
3. Sort by date
4. Filter out documentation-related warnings
5. Fix findings introduced in 2018

![screenshot from 2018-02-07 09-23-20](https://user-images.githubusercontent.com/334256/35905754-9623d2ea-0be8-11e8-9fd0-15f4577abb6f.png)

**Comment by TimvdLippe** [comment]
Shortcut URL: https://demo.teamscale.com/findings.html#list/watchdog/?blacklist=excluded&sort-by=birth&sort-order=descending&baseline=TIMESTAMP%252B1514761200000

**Comment by TimvdLippe** [comment]
I resolved most of the issues in https://github.com/TestRoots/watchdog/pull/279/commits/03c74e5b669a3d77180fe3d8c7eb2631f959d541 Some other warnings like the static variable initialization and non-constant public variables are working as intended.
