### ISSUE TITLE
Improve initial user/project registrations wizards

### ISSUE THREAD

**Issue by TimvdLippe** [TestRoots/watchdog#289]
The current registrations wizards are long and somewhat complicated. We would like to improve the workflow to not lose users to a potentially tedious process. Moreover, the user consent for gathering the data (with an explanation of what data is shared) should be more prominent, to inform the user what we are actually doing. This consent should include a mention that we are allowed to publish the data in an anonymized way (and what "anonymized" actually means in this context).

**Comment by TimvdLippe** [comment]
@Inventitech We have talked about this, but we haven't made a concrete plan just yet. What steps would we like to keep and which ones do we want to skip or consolidate in one screen? I assume we want to remain asking for all characteristics, but in a shortened form?

The workflow would then be:

1. Ask if user is registered, if not in the current screen fill in some data
2. Next screen: ask if there is an existing project. Else fill it in on the current screen.
3. General characteristics regarding the user (e.g. programming experience)

The question is: where should we add the mention of consent? I think the clearest would be to put that on the first screen, instead of letting users fill it in and then show them the message. That is nicest way of conveying that information in my opinion.

**Comment by Inventitech** [comment]
Hi Tim, I like your ideas. 
You are free to remove/adapt the "characteristics" questions (do you use testing/do you have CI/...) to the extent useful you.
Maybe you can give me a list of things you want to ask?

Go ahead :+1:

**Comment by Inventitech** [comment]
Do you have a couple screenshots for me? :-)

**Comment by TimvdLippe** [comment]
No big changes though. You can read the message at https://github.com/TestRoots/watchdog/pull/294/files#diff-f41010c58e5f12981822ba10c16813a5R40 Feel free to suggest textual changes on the language

**Comment by TimvdLippe** [comment]
It's 3 windows right now.

User welcome screen:
![image](https://user-images.githubusercontent.com/5948271/38667025-a76f5260-3e40-11e8-896b-baad52d173cb.png)

User registration:
![image](https://user-images.githubusercontent.com/5948271/38667038-b08f7d5c-3e40-11e8-939d-8b72edc46ec8.png)
Yes:
![image](https://user-images.githubusercontent.com/5948271/38667111-e2ed0bca-3e40-11e8-86f4-5c54201777e5.png)
No:
![image](https://user-images.githubusercontent.com/5948271/38667118-e9aff468-3e40-11e8-866b-dbb435181682.png)
Similar with project registration. No:
![image](https://user-images.githubusercontent.com/5948271/38667166-02e22348-3e41-11e8-926a-e70a9654d331.png)

**Comment by Inventitech** [comment]
Hm, have you seen my comments above?

**Comment by TimvdLippe** [comment]
@Inventitech I have, but I am not sure what you mean. Could you clarify?

**Comment by Inventitech** [comment]
Oh, I forgot to click "Submit" ;) Comment is now [in the code.](https://github.com/TestRoots/watchdog/pull/294/files#diff-f41010c58e5f12981822ba10c16813a5R47)

What do you think about the Project registration? Could we perhaps drop that entire page? I also don't understand why the button "Create new WD project" is there. What's the difference to Finish?

**Comment by TimvdLippe** [comment]
The creation of a project can fail, so that is a different step than finishing the dialog. Therefore the step of creating the project and obtaining its projectid (in a text box) is done first. If that succeeds, the user can finish the dialog. (Similarly to how previously you had a separate page for verification and showing the id)

I think there is still value in asking. The answers are not required (you can create a project without selecting any option). Probably we want to add 1 more question: "... a static analysis tool (e.g. CheckStyle)?"

**Comment by Inventitech** [comment]
Uhh, I think that UI feature is really confusing to users (and was handled better before). 

I agree, they are interesting -- but are you going to use these answers in your research? Would you not want to ask questions about ASATs?

**Comment by TimvdLippe** [comment]
I personally respectfully disagree. To me, the switching between pages was very confusing, especially in the event of the project registration failing. Having this on one page allowing users to modify the data (as it is still in view) makes a lot more sense to me. This probably boils down to personal preference, so I will go around and ask some other students by letting them go through the registration process and note any problems. That way we have quantitative data on what to improve the dialog :+1: 

I am okay with removing all questions and tailor them to my research, but that seems selfish for me. Removing the question means we lose the datapoints from new users regarding the testing. From a research point-of-view, is this a valid proposition? If you are okay with losing these datapoints as they will not be used in later research, I can put questions tailored to ASATs there instead.

**Comment by Inventitech** [comment]
Re your first paragraph: I like that approach very much.

Re the second, I think it is unlikely we are not going to use that data ever -- so why still collect it, if you can't make use of it, either?

**Comment by TimvdLippe** [comment]
> Re the second, I think it is unlikely we are not going to use that data ever -- so why still collect it, if you can't make use of it, either?

All right. I will remove the messages, add new questions for my research and update the JSONTransferer/server logic accordingly.

**Comment by Inventitech** [comment]
@TimvdLippe Could you post an updated screenshot of the first registratoin page so that I can include it in the ethics report? Thanks!

**Comment by TimvdLippe** [comment]
I can do that tomorrow afternoon, then I have my laptop accessible again.

Op do 12 apr. 2018 om 21:52 schreef Moritz Beller <notifications@github.com

**Comment by Inventitech** [comment]
Awesome, thanks, @TimvdLippe :-)

**Comment by Inventitech** [comment]
UI in Eclipse is not satisfactory:

![screenshot from 2018-04-26 17-13-46](https://user-images.githubusercontent.com/334256/39314815-6eaed370-4975-11e8-92f4-66ccb99bc7ba.png)

The position of the icons is weird, the text does not appear where it should. Why is the TU Delft logo not in the upper right corner, but the user icon? The look and feel of the input fields is non-genuine (why are they rounded?)

The operating system field is still an input text field, not a label.
The checkmark symbols do not appear after a successful user verification.

Please test this on a Mac and Windows system, too, and post screenshots here.

One additional comment: Why are the text strings of the wizards duplicated between the Eclipse and IntelliJ versions? They should really be in the core. Please add periods to the end of the sentences, too.

**Comment by TimvdLippe** [comment]
>The position of the icons is weird, the text does not appear where it should. Why is the TU Delft logo not in the upper right corner, but the user icon?

Because I used the same logic as IntelliJ, to keep the code consistent. Happy to introduce differences in each implementation in terms of layout, but we just need to be aware of making such a change in terms of maintaibility. Could you specify what you mean with `where it should`?

> The look and feel of the input fields is non-genuine (why are they rounded?)

I think this is a personal judgement. I personally also prefer the IntelliJ UI over Eclipse, but this just how Eclipse looks. Moreover, the rounded corners are already on master, so this is not an issue in the current PR as well as not a WatchDog issue. I think you need to open a feature request at Eclipse if you would like this addressed in the core Eclipse UI theme.

> The operating system field is still an input text field, not a label.

Ah did that in IntelliJ, but forgot in Eclipse. Duplication FTW.....

> Please test this on a Mac and Windows system, too, and post screenshots here.

This code and look-and-feel should be platform-independent.

> Why are the text strings of the wizards duplicated between the Eclipse and IntelliJ versions? They should really be in the core.

Most of the strings of user and project are in core, because that made sense. I will try to find a sensible location for extracting the user strings. Note that because of the difference in implementation between IntelliJ and Eclipse regarding browser links, this can get a bit annoying. I suppose an `enum` works best in this case.

> Please add periods to the end of the sentences, too.

Sure.

**Comment by TimvdLippe** [comment]
I made some small tweaks to the spacing. Screenshots should now be mostly similar. Note that the "Welcome to WatchDog!"  has been moved, to keep it in-line with our other UI and make it more clear.

Before:

![image](https://user-images.githubusercontent.com/5948271/39432260-477a02b8-4c93-11e8-84a2-32647a396817.png)

After:

![image](https://user-images.githubusercontent.com/5948271/39433205-8df2cd5e-4c95-11e8-9ee7-4143df992ba0.png)

**Comment by Inventitech** [comment]
Why is the text "Welcome to watchdog" in the gray area? Why is the gray area so huge? Why remove the pictograms to distinguish between user and project setup?

**Comment by TimvdLippe** [comment]
> Why is the text "Welcome to watchdog" in the gray area?

As I said in the previous comment: 

> Note that the "Welcome to WatchDog!" has been moved, to keep it in-line with our other UI and make it more clear.

> Why is the gray area so huge?

Because the project registration panel is rather big and Eclipse does not allow a wizard to dynamically change.

> Why remove the pictograms to distinguish between user and project setup?

This should be clear by the new pages so I see no need to add them back. If you still want them back, I can add them, but I would personally be against that.

**Comment by Inventitech** [comment]
Bootup with registered User ID, new project:

Wizard contents are now within the window frame, but the layout remains distorted.

![screenshot from 2018-05-02 10-27-58](https://user-images.githubusercontent.com/334256/39513132-931501b2-4df3-11e8-9162-b3bb81e8c8f3.png)

**Comment by Inventitech** [comment]
User registration is also broken visually in the sign-up wizard. Text is rendered to the right, the flow is visually broken.

Question should not be "Do you have a (user|project) WatchDog registration?", but "Do you have a WatchDog (user|project) registration?". Actually, the question should also ask at least in the case of projects for *this project/workspace*. In fact, maybe an even better question would be Do you want to create a new ... 
Since the icons are gone, could we highlight user or project?

![screenshot from 2018-05-02 10-29-58](https://user-images.githubusercontent.com/334256/39513205-de957086-4df3-11e8-9c1e-f2e354d57ab9.png)

**Comment by Inventitech** [comment]
After registering a user, why is the field not aligned with all the other fields in the wizard? Why is it using a non-editable input box and not a label like Linux?

![screenshot from 2018-05-02 10-37-37](https://user-images.githubusercontent.com/334256/39513542-03d17092-4df5-11e8-8519-bb482fb87f2c.png)

**Comment by Inventitech** [comment]
When I go back on the above page and Next, the Create new WatchDog user button is not locked, so people can create an arbitrary number of WatchDog users.

**Comment by Inventitech** [comment]
Clicking Cancel in the above step brings up this weird message:

![screenshot from 2018-05-02 10-43-21](https://user-images.githubusercontent.com/334256/39513764-afb18f0a-4df5-11e8-90bd-92b9cb2f2c52.png)

No, I do not want to create a project, I just cancelled it!!

Btw., the content of the wizard is initially distorted (I was not fast enough to capture it) and relayouted properly after switching focus back to Eclipse.

**Comment by Inventitech** [comment]
There is a horizontal gap between the two questions. Why are the questions not vertically aligned?

**Comment by TimvdLippe** [comment]
I have followed your steps, but was unable to reproduce these visual issues on my machine. Since this is quite hard to debug, I took a completely different approach. The code now uses `composite.pack()` instead of the magic values. This should hopefully fix the issues on your machine as well. Could you let me know if it is now working as intended?

> Question should not be "Do you have a (user|project) WatchDog registration?", but "Do you have a WatchDog (user|project) registration?". Actually, the question should also ask at least in the case of projects for this project/workspace. In fact, maybe an even better question would be Do you want to create a new ...

Good suggestion :+1: , I have updated the wording to the following two (and swapped the meaning of the buttons):
```
Do you want to create a new WatchDog (user|project) registration?
```

> After registering a user, why is the field not aligned with all the other fields in the wizard?

Since this field is the output from the form, the visual distinction accentuates the difference between input and output. Moreover, the field is a lot longer than the other fields, so this field should be longer than the others and thus not fit in the grid layout.

> When I go back on the above page and Next, the Create new WatchDog user button is not locked, so people can create an arbitrary number of WatchDog users.

Good catch. I indeed forgot to disable it on that menu. Actually, to prevent these kind of issues I have abstracted away this logic to reduce duplication and prevent these kind of issues :+1: 

> Why is it using a non-editable input box and not a label like Linux?

Because (at least on my machine) you can not select the text (to copy) of the label, but you can in an editbox. Since the user should be able to copy the ID, a label would not work.

> No, I do not want to create a project, I just cancelled it!!

This was one of the feedback points of last week IRL meeting (to also open the window if the project ID is not found). I have updated the logic to prevent this from happening.

> Btw., the content of the wizard is initially distorted (I was not fast enough to capture it) and relayouted properly after switching focus back to Eclipse.

With the new `composite.pack()` method, I think this should be resolved as well.

> There is a horizontal gap between the two questions. Why are the questions not vertically aligned?

This appears to be a default margin in the RowLayout. I have explicitly removed the margin from these layouts to fix the issue.

**Comment by Inventitech** [comment]
![screenshot from 2018-05-02 16-35-51](https://user-images.githubusercontent.com/334256/39531862-70627030-4e2c-11e8-83ef-92d1fcb4a065.png)

The size of the input field does not fit an entire WatchDog ID.

**Comment by Inventitech** [comment]
The Verify button is horizontally stretching, but the register button is not. I actually like that. Also, especially in this big dialog and when only Finish is available, people might miss the register button on the left. 

![screenshot from 2018-05-02 16-36-04](https://user-images.githubusercontent.com/334256/39531972-ab8cb9f4-4e2c-11e8-9626-21ffc75403a6.png)

Treat and layout the verify and register buttons in the same way?

**Comment by TimvdLippe** [comment]
Layout of the output text should now be improved:
![image](https://user-images.githubusercontent.com/5948271/39663991-a4836818-507c-11e8-8e03-3f7e42e50676.png)

And the ID field should be sufficiently large:
![image](https://user-images.githubusercontent.com/5948271/39664088-4c547950-507e-11e8-8ac8-2ac06f3f42cb.png)

**Comment by TimvdLippe** [comment]
On IntelliJ:

![image](https://user-images.githubusercontent.com/5948271/39664158-99a751ea-507f-11e8-969c-8cd32ea0510c.png)

**Comment by Inventitech** [comment]
Fine with this, no need for a PR later. Looking good. Are there extraneous spaces in front of the links in IntelliJ?

**Comment by TimvdLippe** [comment]
Yes they are, but that is the Swing layout manager I can not change. That is because IntellIJ forces the text to be separated from the clickable link. In Eclipse you can make this in 1 element and it just works.
