### ISSUE TITLE
[Blocking] Observe Conditions by TU Delft Ethics board

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#307]
This demands changes in the registration. We could possibly include these changes in our plugin license, which is the correct -- but not a very prominent -- place. To be on the safe side, I would add something on the Welcome page along the lines of "We store all WatchDog data for 5 years. In case of complaints please contact us" (link to contact page)

[Letter_of_approval390.pdf](https://github.com/TestRoots/watchdog/files/1970345/Letter_of_approval390.pdf)

**Comment by TimvdLippe** [comment]
Am I correct to deduce the following action points from this issue?

1. The informed consent is added to the license (not sure where we store this file actually)
1. We add a new line in the welcome screen regarding the 5 year data retention
1. We add a new line in the welcome screen with the contact address (info -AT- testroots.org)

**Comment by Inventitech** [comment]
No, unfortunately this is still WIP, we will meet with the Ethics person next week to see how we can go forward.

**Comment by Inventitech** [comment]
The 5 year data retention has been lifted. 

So i would say. Action points for me
- [ ] Add informed consent to license

Action points for Tim:
- [ ] Add a new line regarding infinite storage of data (until revocation to below email address) and that we will publish the strictly anonymized data set
- [ ] We add a new line in the welcome screen with the contact address (info -AT- testroots.org)

(Maybe the existing lines have to be a bit reworked to accommodate this change, too.)

**Comment by TimvdLippe** [comment]
Action point of @Inventitech also addressed in #313
