### ISSUE TITLE
When WatchDog server returns 500, the user does not see this

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#314]
Trying to register a new user, when this is not successful, the UI does not change at all.

**Comment by TimvdLippe** [comment]
Is this Eclipse or IntelliJ or both?

**Comment by TimvdLippe** [comment]
Oh it is actually easy. We have to update the following snippet to catch Exception instead:

```java
try {
			userId = new JsonTransferer().registerNewUser(user);
		} catch (ServerCommunicationException exception) {
			this.createFailureMessage(USER_CREATION_MESSAGE_FAILURE, exception);

			return false;
		}
```

**Comment by TimvdLippe** [comment]
Okay, it is not that easy sadly. It seems we are already catching this exception appropriately down in the `JsonTransferer`
