### ISSUE TITLE
Proxy support in intellij

### ISSUE THREAD

**Issue by mt3o** [TestRoots/watchdog#317]
Hi!
I tried to use the plugin in IntelliJ in a corporate env, behind ZScaler proxy and failed, despite having a proxy set up in IntelliJ settings. I think the plugin tries to reach the server directly, without acknowledging that there is a proxy that should be used. This happened to me during account creation. 
I know I can walkaround this issue by registering via browser, but if IDE sends data online - it will fail due to ZScaler.

**Comment by Inventitech** [comment]
Hi Teodor,

Good comment and remark. Indeed, we don't respect the proxy settings in the IDE. Unfortunately, for now, there are no plans to add support for this (sorry!), so I'm closing this.

Moritz
