### ISSUE TITLE
Randomize placement of project slider

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#318]
This issue consists of the following substeps:
- [x] Add slider back for Eclipse
- [x] Add slider back for IntelliJ
- [x] Randomize slider position
- [x] Transfer slider position

**Comment by Inventitech** [comment]
@TimvdLippe would you be willing to review this once I am done?

**Comment by TimvdLippe** [comment]
I can do static reviews, but I can not run the code.

**Comment by Inventitech** [comment]
Ok, cool, thx. I'll ping you once done.

**Comment by Inventitech** [comment]
Done. @TimvdLippe, would appreciate your feedback on this one.

Pretty flabbergasted by the number of issues I came across while implementing this TBH (#320, #319, and additionally commits 8b29992, 11fda2b).

**Comment by TimvdLippe** [comment]
@Inventitech I can't find a PR for this issue. Did I miss it? Would like to have a place where I can post the review comments 😄

**Comment by Inventitech** [comment]
Hi Tim,

Yap, sorry, I didn't think of the possibility to get a review on this at first, so committed directly to master. I'll see if I can at least get a decent diff.

Will get back.

**Comment by Inventitech** [comment]
I created #321 so you can review the changes. Thanks!
