### ISSUE TITLE
Project registration is not working in IntelliJ

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#320]
When registering a new project, this id is never set in IntelliJ. Investigate why

**Comment by Inventitech** [comment]
Interesting, @TimvdLippe did you not notice in your analysis that there wasn't a lot of intervals for newly created IntelliJ projects?

**Comment by TimvdLippe** [comment]
My analysis showed that there were quite some IntelliJ/Android Studio registrations, so I am/was not aware of any registration issues.

**Comment by Inventitech** [comment]
Yeah, as I said, registration does work, but I'd be surprised if everyone manually entered the newly generated ID back in the settings.

**Comment by Inventitech** [comment]
Closing as problem is solved.
